<a href="https://colab.research.google.com/github/AkhzarFarhan/Data-Mining/blob/master/DM_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##2. Create dataitem sample

### Importing random and numpy library

In [0]:
import random
import numpy as np

In [2]:
sample = [random.randint(0, 99) for i in range(20)]
sample

[8, 50, 91, 60, 15, 16, 67, 88, 36, 12, 97, 25, 32, 42, 4, 73, 52, 6, 74, 86]

###Largest item

In [3]:
max(sample)

97

###Smallest item

In [4]:
min(sample)

4

###Number of items

In [5]:
len(sample)

20

###Standard Deviation

In [6]:
np.std(sample)

30.62694891757911

##3. Create a Matrix

###2D Matrix

In [7]:
a = np.array([[1, 1, 3], [5, 2, 6], [-2, -1, -3]])
a

array([[ 1,  1,  3],
       [ 5,  2,  6],
       [-2, -1, -3]])

###Importing linear algebra as linalg

In [8]:
np.linalg.matrix_power(a, 3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
a[-1] = a[-1] + a[-2]
a

array([[1, 1, 3],
       [5, 2, 6],
       [3, 1, 3]])

In [10]:
np.array([[int(i) for i in range(k, k+5)] for k in range(4)])

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])